name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild Dumper-7.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          **/*.exe
          **/*.dll
          **/*.pdb
          **/*.lib
          **/*.obj
          **/*.tlb
          **/*.map
          **/*.exp
